### ISSUE TITLE
Crash upon attempting to launch NMS View

### ISSUE THREAD

**Issue by Drullkus** [HugoPeters/NMS-Tools#1]
There appears to be a file missing. (VCRUNTIME140.dll)

![explorer_2016-09-12_20-07-57](https://cloud.githubusercontent.com/assets/5010174/18460304/2ca61faa-7925-11e6-8482-2d1f5986e4b5.png)

**Comment by Drullkus** [comment]
Friend suggested I download the [V C++ Distributables](https://www.microsoft.com/en-in/download/details.aspx?id=48145). Works as a workaround

**Comment by HugoPeters** [comment]
That's actually the only solution, VC++ runtime is required for this to run.
