### ISSUE TITLE
Usage of NMS-Extract unclear

### ISSUE THREAD

**Issue by Drullkus** [HugoPeters/NMS-Tools#2]
I am confused as to how the NMS-Extract tool would be used. Attempting to open the exe just causes the program to close itself after launching, with no output visible. The github README lacks further information :/

EDIT: Went to source code. [Found this.](https://github.com/HugoPeters/NMS-Tools/blob/master/NMS-Extract/Source/Program.cs#L35) Turns out it's a command prompt tool.

Some clarification on the ReadMe would be helpful to future explorers :)

**Comment by HugoPeters** [comment]
I'll update the README :)
